name: Update README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script to update README
        run: python update_readme.py
      - name: Push changes
        uses: actions/github-script@v4
        with:
          script: |
            const gh = require('@actions/github');
            const octokit = new gh.GitHub('${{ secrets.PAT }}');
            octokit.repos.createOrUpdateFileContents({
              owner: '${{ github.repository_owner }}',
              repo: '${{ github.repository }}',
              path: 'README.md',
              message: 'Update README',
              content: Buffer.from(fs.readFileSync('README.md')).toString('base64'),
              sha: '${{ gh.event.head_commit.id }}'
            });
